---
development:
  cloud_name: smartnelly
  api_key: '268694396268364'
  api_secret: Arv3OVGiCmthNpQSy1tKiO6ONuo
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: smartnelly
  api_key: '268694396268364'
  api_secret: Arv3OVGiCmthNpQSy1tKiO6ONuo
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: smartnelly
  api_key: '268694396268364'
  api_secret: Arv3OVGiCmthNpQSy1tKiO6ONuo
  enhance_image_tag: true
  static_file_support: false
